version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27017:27017
    profiles:
      - with-mongo
      

  backend:
    build: ./server
    ports:
      - "3001:3000"
    # depends_on:
    #   - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/mydatabase

  front:
    build: ./front
    ports:
      - "80:80"
    # ports:
    #   - "80:5173"
    # depends_on:
    #   - mongo
    
